accessWidener   v1  named
accessible	class	net/minecraft/server/world/ThreadedAnvilChunkStorage$EntityTracker
extendable	class	net/minecraft/server/world/ThreadedAnvilChunkStorage$EntityTracker
accessible	class	net/minecraft/recipe/Ingredient$Entry
extendable	class	net/minecraft/recipe/Ingredient$Entry
accessible	class	net/minecraft/recipe/Ingredient$StackEntry
extendable	class	net/minecraft/recipe/Ingredient$StackEntry
accessible	method	net/minecraft/block/DispenserBlock	dispense	(Lnet/minecraft/server/world/ServerWorld;Lnet/minecraft/util/math/BlockPos;)V
accessible	method	net/minecraft/entity/decoration/AbstractDecorationEntity	setFacing	(Lnet/minecraft/util/math/Direction;)V
accessible	method	net/minecraft/entity/mob/SlimeEntity	setSize	(IZ)V
accessible	field	net/minecraft/advancement/PlayerAdvancementTracker	advancementToProgress	Ljava/util/Map;
accessible	field	net/minecraft/server/ServerAdvancementLoader	GSON	Lcom/google/gson/Gson;
accessible	field	net/minecraft/server/ServerAdvancementLoader	manager	Lnet/minecraft/advancement/AdvancementManager;
accessible	field	net/minecraft/advancement/AdvancementManager	advancements	Ljava/util/Map;
accessible	field	net/minecraft/entity/attribute/ClampedEntityAttribute	maxValue	D
accessible	field	net/minecraft/block/AbstractBlock$AbstractBlockState	hardness	F
accessible	field	net/minecraft/block/DispenserBlock	BEHAVIORS	Ljava/util/Map;
accessible	method	net/minecraft/block/JukeboxBlock	removeRecord	(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)V
accessible	field	net/minecraft/block/ShulkerBoxBlock	color	Lnet/minecraft/util/DyeColor;
accessible	field	net/minecraft/entity/boss/BossBar	color	Lnet/minecraft/entity/boss/BossBar$Color;
accessible	field	net/minecraft/entity/boss/BossBar	style	Lnet/minecraft/entity/boss/BossBar$Style;
accessible	field	net/minecraft/entity/boss/BossBar	name	Lnet/minecraft/text/Text;
accessible	method	net/minecraft/entity/boss/ServerBossBar	sendPacket	(Lnet/minecraft/network/packet/s2c/play/BossBarS2CPacket$Type;)V
accessible	field	net/minecraft/entity/boss/ServerBossBar	visible	Z
accessible	field	net/minecraft/text/TextColor	name	Ljava/lang/String;
accessible	field	net/minecraft/inventory/ContainerLock	key	Ljava/lang/String;
accessible	field	net/minecraft/world/chunk/WorldChunk	entitySections	[Lnet/minecraft/util/collection/TypeFilterableList;
accessible	field	net/minecraft/world/chunk/WorldChunk	heightmaps	Ljava/util/Map;
accessible	field	net/minecraft/world/chunk/WorldChunk	loadedToWorld	Z
accessible	field	net/minecraft/world/chunk/WorldChunk	blockEntities	Ljava/util/Map;
accessible	field	net/minecraft/world/chunk/WorldChunk	world	Lnet/minecraft/world/World;
accessible	field	net/minecraft/server/world/ChunkTicketManager	ticketsByPosition	Lit/unimi/dsi/fastutil/longs/Long2ObjectOpenHashMap;
accessible	field	net/minecraft/server/world/ServerChunkManager	spawnAnimals	Z
accessible	field	net/minecraft/server/world/ServerChunkManager	spawnMonsters	Z
accessible	field	net/minecraft/server/world/ServerChunkManager	chunkGenerator	Lnet/minecraft/world/gen/chunk/ChunkGenerator;
accessible	field	net/minecraft/world/chunk/ChunkSection	PALETTE	Lnet/minecraft/world/chunk/Palette;
accessible	field	net/minecraft/server/command/ServerCommandSource	output	Lnet/minecraft/server/command/CommandOutput;
accessible	field	net/minecraft/screen/AnvilScreenHandler	levelCost	Lnet/minecraft/screen/Property;
accessible	field	net/minecraft/screen/AnvilScreenHandler	newItemName	Ljava/lang/String;
accessible	field	net/minecraft/screen/Generic3x3ContainerScreenHandler	inventory	Lnet/minecraft/inventory/Inventory;
accessible	field	net/minecraft/screen/CraftingScreenHandler	context	Lnet/minecraft/screen/ScreenHandlerContext;
accessible	field	net/minecraft/world/level/storage/LevelStorage$Session	directory	Ljava/nio/file/Path;
accessible	field	net/minecraft/world/level/storage/LevelStorage	savesDirectory	Ljava/nio/file/Path;
accessible	method	net/minecraft/datafixer/fix/BlockStateFlattening	putStates	(ILjava/lang/String;[Ljava/lang/String;)V
accessible	field	net/minecraft/datafixer/fix/ItemIdFix	NUMERICAL_ID_TO_STRING_ID_MAP	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
accessible	field	net/minecraft/datafixer/fix/ItemSpawnEggFix	DAMAGE_TO_ENTITY_IDS	[Ljava/lang/String;
accessible	field	net/minecraft/server/dedicated/MinecraftDedicatedServer	rconCommandOutput	Lnet/minecraft/server/rcon/RconCommandOutput;
accessible	field	net/minecraft/entity/boss/dragon/EnderDragonFight	bossBar	Lnet/minecraft/entity/boss/ServerBossBar;
accessible	field	net/minecraft/entity/boss/dragon/EnderDragonFight	dragonUuid	Ljava/util/UUID;
accessible	field	net/minecraft/entity/boss/dragon/EnderDragonFight	exitPortalLocation	Lnet/minecraft/util/math/BlockPos;
accessible	method	net/minecraft/entity/boss/dragon/EnderDragonFight	generateEndPortal	(Z)V
accessible	method	net/minecraft/entity/boss/dragon/EnderDragonFight	findEndPortal	()Lnet/minecraft/block/pattern/BlockPattern$Result;
accessible	field	net/minecraft/entity/boss/dragon/EnderDragonFight	dragonSpawnState	Lnet/minecraft/entity/boss/dragon/EnderDragonSpawnState;
accessible	method	net/minecraft/entity/boss/dragon/EnderDragonFight	setSpawnState	(Lnet/minecraft/entity/boss/dragon/EnderDragonSpawnState;)V
accessible	field	net/minecraft/entity/boss/dragon/EnderDragonFight	world	Lnet/minecraft/server/world/ServerWorld;
accessible	field	net/minecraft/entity/Entity	fireTicks	I
accessible	method	net/minecraft/entity/Entity	getFlag	(I)Z
accessible	method	net/minecraft/entity/Entity	getBurningDuration	()I
accessible	method	net/minecraft/entity/Entity	getSavedEntityId	()Ljava/lang/String;
accessible	field	net/minecraft/entity/Entity	glowing	Z
accessible	field	net/minecraft/entity/Entity	touchingWater	Z
accessible	field	net/minecraft/entity/Entity	passengerList	Ljava/util/List;
accessible	field	net/minecraft/entity/Entity	netherPortalCooldown	I
accessible	method	net/minecraft/entity/Entity	setFlag	(IZ)V
accessible	field	net/minecraft/entity/passive/AnimalEntity	lovingPlayer	Ljava/util/UUID;
accessible	field	net/minecraft/entity/passive/AnimalEntity	loveTicks	I
accessible	field	net/minecraft/entity/AreaEffectCloudEntity	durationOnUse	I
accessible	field	net/minecraft/entity/AreaEffectCloudEntity	radiusOnUse	F
accessible	field	net/minecraft/entity/AreaEffectCloudEntity	radiusGrowth	F
accessible	field	net/minecraft/entity/AreaEffectCloudEntity	reapplicationDelay	I
accessible	field	net/minecraft/entity/AreaEffectCloudEntity	waitTime	I
accessible	field	net/minecraft/entity/decoration/ArmorStandEntity	bodyRotation	Lnet/minecraft/util/math/EulerAngle;
accessible	field	net/minecraft/entity/decoration/ArmorStandEntity	disabledSlots	I
accessible	field	net/minecraft/entity/decoration/ArmorStandEntity	headRotation	Lnet/minecraft/util/math/EulerAngle;
accessible	field	net/minecraft/entity/decoration/ArmorStandEntity	leftArmRotation	Lnet/minecraft/util/math/EulerAngle;
accessible	field	net/minecraft/entity/decoration/ArmorStandEntity	leftLegRotation	Lnet/minecraft/util/math/EulerAngle;
accessible	field	net/minecraft/entity/decoration/ArmorStandEntity	rightArmRotation	Lnet/minecraft/util/math/EulerAngle;
accessible	field	net/minecraft/entity/decoration/ArmorStandEntity	rightLegRotation	Lnet/minecraft/util/math/EulerAngle;
accessible	method	net/minecraft/entity/decoration/ArmorStandEntity	setShowArms	(Z)V
accessible	method	net/minecraft/entity/decoration/ArmorStandEntity	setHideBasePlate	(Z)V
accessible	method	net/minecraft/entity/decoration/ArmorStandEntity	setMarker	(Z)V
accessible	method	net/minecraft/entity/decoration/ArmorStandEntity	setSmall	(Z)V
accessible	field	net/minecraft/entity/projectile/PersistentProjectileEntity	life	I
accessible	field	net/minecraft/entity/projectile/PersistentProjectileEntity	inGround	Z
accessible	field	net/minecraft/entity/projectile/PersistentProjectileEntity	punch	I
accessible	field	net/minecraft/entity/passive/BeeEntity	cannotEnterHiveTicks	I
accessible	field	net/minecraft/entity/passive/BeeEntity	hivePos	Lnet/minecraft/util/math/BlockPos;
accessible	method	net/minecraft/entity/passive/BeeEntity	setHasNectar	(Z)V
accessible	method	net/minecraft/entity/passive/BeeEntity	setHasStung	(Z)V
accessible	method	net/minecraft/entity/mob/CreeperEntity	explode	()V
accessible	field	net/minecraft/entity/mob/CreeperEntity	explosionRadius	I
accessible	field	net/minecraft/entity/mob/CreeperEntity	fuseTime	I
accessible	field	net/minecraft/entity/boss/dragon/EnderDragonEntity	parts	[Lnet/minecraft/entity/boss/dragon/EnderDragonPart;
accessible	field	net/minecraft/entity/EyeOfEnderEntity	lifespan	I
accessible	field	net/minecraft/entity/EyeOfEnderEntity	dropsItem	Z
accessible	field	net/minecraft/entity/EyeOfEnderEntity	targetX	D
accessible	field	net/minecraft/entity/EyeOfEnderEntity	targetY	D
accessible	field	net/minecraft/entity/EyeOfEnderEntity	targetZ	D
accessible	field	net/minecraft/entity/ExperienceOrbEntity	amount	I
accessible	field	net/minecraft/entity/FallingBlockEntity	hurtEntities	Z
accessible	method	net/minecraft/entity/projectile/AbstractFireballEntity	getItem	()Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/entity/projectile/FireworkRocketEntity	ITEM	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/projectile/FireworkRocketEntity	SHOT_AT_ANGLE	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/projectile/FireworkRocketEntity	lifeTime	I
accessible	method	net/minecraft/entity/passive/FishEntity	isFromBucket	()Z
accessible	field	net/minecraft/entity/passive/FoxEntity	OWNER	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/passive/FoxEntity	OTHER_TRUSTED	Lnet/minecraft/entity/data/TrackedData;
accessible	method	net/minecraft/entity/passive/FoxEntity	setType	(Lnet/minecraft/entity/passive/FoxEntity$Type;)V
accessible	method	net/minecraft/entity/passive/FoxEntity	setSleeping	(Z)V
accessible	field	net/minecraft/entity/mob/GuardianEntity	wanderGoal	Lnet/minecraft/entity/ai/goal/WanderAroundGoal;
accessible	field	net/minecraft/entity/decoration/AbstractDecorationEntity	attachmentPos	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/entity/mob/HoglinEntity	cannotBeHunted	Z
accessible	field	net/minecraft/entity/mob/HoglinEntity	timeInOverworld	I
accessible	method	net/minecraft/entity/mob/HoglinEntity	isImmuneToZombification	()Z
accessible	method	net/minecraft/entity/passive/HorseEntity	setVariant	(Lnet/minecraft/entity/passive/HorseColor;Lnet/minecraft/entity/passive/HorseMarking;)V
accessible	field	net/minecraft/entity/passive/HorseBaseEntity	items	Lnet/minecraft/inventory/SimpleInventory;
accessible	method	net/minecraft/entity/passive/HorseBaseEntity	onChestedStatusChanged	()V
accessible	method	net/minecraft/entity/player/PlayerEntity	closeHandledScreen	()V
accessible	method	net/minecraft/entity/player/PlayerEntity	setShoulderEntityLeft	(Lnet/minecraft/nbt/CompoundTag;)V
accessible	method	net/minecraft/entity/player/PlayerEntity	setShoulderEntityRight	(Lnet/minecraft/nbt/CompoundTag;)V
accessible	field	net/minecraft/entity/player/PlayerEntity	sleepTimer	I
accessible	method	net/minecraft/entity/mob/SpellcastingIllagerEntity	getSpell	()Lnet/minecraft/entity/mob/SpellcastingIllagerEntity$Spell;
accessible	field	net/minecraft/entity/mob/MobEntity	armorDropChances	[F
accessible	field	net/minecraft/entity/mob/MobEntity	handDropChances	[F
accessible	field	net/minecraft/entity/mob/MobEntity	lootTable	Lnet/minecraft/util/Identifier;
accessible	field	net/minecraft/entity/mob/MobEntity	lootTableSeed	J
accessible	field	net/minecraft/entity/mob/MobEntity	persistent	Z
accessible	field	net/minecraft/entity/ItemEntity	age	I
accessible	field	net/minecraft/entity/ItemEntity	pickupDelay	I
accessible	field	net/minecraft/entity/decoration/ItemFrameEntity	fixed	Z
accessible	field	net/minecraft/entity/LightningEntity	cosmetic	Z
accessible	field	net/minecraft/entity/LivingEntity	STUCK_ARROW_COUNT	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/LivingEntity	HEALTH	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/LivingEntity	activeStatusEffects	Ljava/util/Map;
accessible	field	net/minecraft/entity/LivingEntity	lastAttackedTime	I
accessible	field	net/minecraft/entity/LivingEntity	attackingPlayer	Lnet/minecraft/entity/player/PlayerEntity;
accessible	field	net/minecraft/entity/LivingEntity	lastDamageTaken	F
accessible	field	net/minecraft/entity/LivingEntity	attacker	Lnet/minecraft/entity/LivingEntity;
accessible	field	net/minecraft/entity/LivingEntity	effectsChanged	Z
accessible	method	net/minecraft/entity/passive/LlamaEntity	setStrength	(I)V
accessible	field	net/minecraft/entity/vehicle/CommandBlockMinecartEntity	COMMAND	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/vehicle/StorageMinecartEntity	lootTableId	Lnet/minecraft/util/Identifier;
accessible	field	net/minecraft/entity/vehicle/StorageMinecartEntity	lootSeed	J
accessible	field	net/minecraft/entity/vehicle/FurnaceMinecartEntity	fuel	I
accessible	method	net/minecraft/entity/passive/MooshroomEntity	setType	(Lnet/minecraft/entity/passive/MooshroomEntity$Type;)V
accessible	field	net/minecraft/entity/passive/PigEntity	saddledComponent	Lnet/minecraft/entity/SaddledComponent;
accessible	field	net/minecraft/entity/mob/PiglinEntity	cannotHunt	Z
accessible	field	net/minecraft/entity/mob/AbstractPiglinEntity	timeInOverworld	I
accessible	method	net/minecraft/entity/mob/AbstractPiglinEntity	isImmuneToZombification	()Z
accessible	field	net/minecraft/entity/mob/PillagerEntity	inventory	Lnet/minecraft/inventory/SimpleInventory;
accessible	field	net/minecraft/server/network/ServerPlayerEntity	joinInvulnerabilityTicks	I
accessible	field	net/minecraft/server/network/ServerPlayerEntity	syncedExperience	I
accessible	method	net/minecraft/server/network/ServerPlayerEntity	incrementScreenHandlerSyncId	()V
accessible	field	net/minecraft/server/network/ServerPlayerEntity	removedEntities	Ljava/util/List;
accessible	method	net/minecraft/server/network/ServerPlayerEntity	worldChanged	(Lnet/minecraft/server/world/ServerWorld;)V
accessible	field	net/minecraft/server/network/ServerPlayerEntity	inTeleportationState	Z
accessible	method	net/minecraft/entity/projectile/thrown/PotionEntity	isLingering	()Z
accessible	method	net/minecraft/entity/projectile/thrown/ThrownItemEntity	getItem	()Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/entity/mob/ShulkerEntity	COLOR	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/projectile/SpectralArrowEntity	duration	I
accessible	field	net/minecraft/entity/passive/StriderEntity	saddledComponent	Lnet/minecraft/entity/SaddledComponent;
accessible	field	net/minecraft/entity/projectile/TridentEntity	tridentStack	Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/entity/projectile/ArrowEntity	effects	Ljava/util/Set;
accessible	method	net/minecraft/entity/projectile/ArrowEntity	setColor	(I)V
accessible	field	net/minecraft/entity/TntEntity	causingEntity	Lnet/minecraft/entity/LivingEntity;
accessible	method	net/minecraft/entity/passive/VillagerEntity	levelUp	()V
accessible	field	net/minecraft/entity/boss/WitherEntity	bossBar	Lnet/minecraft/entity/boss/ServerBossBar;
accessible	field	net/minecraft/entity/mob/ZombieEntity	CONVERTING_IN_WATER	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/mob/ZombieEntity	ticksUntilWaterConversion	I
accessible	method	net/minecraft/entity/mob/ZombieEntity	setTicksUntilWaterConversion	(I)V
accessible	field	net/minecraft/entity/mob/ZombieVillagerEntity	CONVERTING	Lnet/minecraft/entity/data/TrackedData;
accessible	field	net/minecraft/entity/mob/ZombieVillagerEntity	conversionTimer	I
accessible	field	net/minecraft/entity/mob/ZombieVillagerEntity	converter	Ljava/util/UUID;
accessible	method	net/minecraft/entity/mob/ZombieVillagerEntity	setConverting	(Ljava/util/UUID;I)V
accessible	field	net/minecraft/util/Formatting	code	C
accessible	field	net/minecraft/world/explosion/Explosion	entity	Lnet/minecraft/entity/Entity;
accessible	field	net/minecraft/entity/player/HungerManager	exhaustion	F
accessible	field	net/minecraft/entity/player/HungerManager	foodLevel	I
accessible	field	net/minecraft/entity/player/HungerManager	foodSaturationLevel	F
accessible	method	net/minecraft/world/GameRules$Rule	changed	(Lnet/minecraft/server/MinecraftServer;)V
accessible	field	net/minecraft/state/State	PROPERTY_MAP_PRINTER	Ljava/util/function/Function;
accessible	field	net/minecraft/inventory/CraftingInventory	handler	Lnet/minecraft/screen/ScreenHandler;
accessible	field	net/minecraft/inventory/DoubleInventory	first	Lnet/minecraft/inventory/Inventory;
accessible	field	net/minecraft/inventory/DoubleInventory	second	Lnet/minecraft/inventory/Inventory;
accessible	field	net/minecraft/village/MerchantInventory	recipeIndex	I
accessible	field	net/minecraft/inventory/SimpleInventory	stacks	Lnet/minecraft/util/collection/DefaultedList;
accessible	method	net/minecraft/item/ItemUsageContext	<init>	(Lnet/minecraft/world/World;Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/util/Hand;Lnet/minecraft/item/ItemStack;Lnet/minecraft/util/hit/BlockHitResult;)V
accessible	field	net/minecraft/item/WallStandingBlockItem	wallBlock	Lnet/minecraft/block/Block;
accessible	field	net/minecraft/item/BucketItem	fluid	Lnet/minecraft/fluid/Fluid;
accessible	class	net/minecraft/entity/player/ItemCooldownManager$Entry
extendable	class	net/minecraft/entity/player/ItemCooldownManager$Entry
accessible	field	net/minecraft/entity/player/ItemCooldownManager$Entry	endTick	I
accessible	field	net/minecraft/entity/player/ItemCooldownManager	entries	Ljava/util/Map;
accessible	field	net/minecraft/entity/player/ItemCooldownManager	tick	I
accessible	method	net/minecraft/server/ServerConfigEntry	getKey	()Ljava/lang/Object;
accessible	method	net/minecraft/server/Main	forceUpgradeWorld	(Lnet/minecraft/world/level/storage/LevelStorage$Session;Lcom/mojang/datafixers/DataFixer;ZLjava/util/function/BooleanSupplier;Lcom/google/common/collect/ImmutableSet;)V
accessible	field	net/minecraft/village/TradeOffer	priceMultiplier	F
accessible	field	net/minecraft/village/TradeOffer	rewardingPlayerExperience	Z
accessible	field	net/minecraft/village/TradeOffer	sellItem	Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/village/TradeOffer	uses	I
accessible	field	net/minecraft/village/TradeOffer	merchantExperience	I
accessible	field	net/minecraft/server/MinecraftServer	registryManager	Lnet/minecraft/util/registry/DynamicRegistryManager$Impl;
accessible	field	net/minecraft/server/MinecraftServer	dataFixer	Lcom/mojang/datafixers/DataFixer;
accessible	field	net/minecraft/server/MinecraftServer	serverResourceManager	Lnet/minecraft/resource/ServerResourceManager;
accessible	field	net/minecraft/server/MinecraftServer	workerExecutor	Ljava/util/concurrent/Executor;
accessible	method	net/minecraft/server/MinecraftServer	prepareStartRegion	(Lnet/minecraft/server/WorldGenerationProgressListener;)V
accessible	field	net/minecraft/server/MinecraftServer	serverThread	Ljava/lang/Thread;
accessible	field	net/minecraft/server/MinecraftServer	worldGenerationProgressListenerFactory	Lnet/minecraft/server/WorldGenerationProgressListenerFactory;
accessible	field	net/minecraft/server/MinecraftServer	saveHandler	Lnet/minecraft/world/WorldSaveHandler;
accessible	field	net/minecraft/server/MinecraftServer	worlds	Ljava/util/Map;
accessible	method	net/minecraft/world/MobSpawnerLogic	getEntityId	()Lnet/minecraft/util/Identifier;
accessible	field	net/minecraft/world/MobSpawnerLogic	maxNearbyEntities	I
accessible	field	net/minecraft/world/MobSpawnerLogic	maxSpawnDelay	I
accessible	field	net/minecraft/world/MobSpawnerLogic	minSpawnDelay	I
accessible	field	net/minecraft/world/MobSpawnerLogic	spawnPotentials	Ljava/util/List;
accessible	field	net/minecraft/world/MobSpawnerLogic	requiredPlayerRange	I
accessible	field	net/minecraft/world/MobSpawnerLogic	spawnCount	I
accessible	field	net/minecraft/world/MobSpawnerLogic	spawnEntry	Lnet/minecraft/world/MobSpawnerEntry;
accessible	field	net/minecraft/world/MobSpawnerLogic	spawnDelay	I
accessible	field	net/minecraft/world/MobSpawnerLogic	spawnRange	I
accessible	method	net/minecraft/nbt/StringNbtReader	parseTagPrimitiveArray	()Lnet/minecraft/nbt/Tag;
accessible	method	net/minecraft/nbt/StringNbtReader	parsePrimitive	(Ljava/lang/String;)Lnet/minecraft/nbt/Tag;
accessible	field	net/minecraft/network/ClientConnection	channel	Lio/netty/channel/Channel;
accessible	field	net/minecraft/network/ClientConnection	address	Ljava/net/SocketAddress;
accessible	field	net/minecraft/network/packet/c2s/handshake/HandshakeC2SPacket	address	Ljava/lang/String;
accessible	field	net/minecraft/network/packet/c2s/handshake/HandshakeC2SPacket	port	I
accessible	field	net/minecraft/network/packet/c2s/play/CustomPayloadC2SPacket	data	Lnet/minecraft/network/PacketByteBuf;
accessible	field	net/minecraft/network/packet/c2s/play/CustomPayloadC2SPacket	channel	Lnet/minecraft/util/Identifier;
accessible	field	net/minecraft/network/packet/c2s/play/ResourcePackStatusC2SPacket	status	Lnet/minecraft/network/packet/c2s/play/ResourcePackStatusC2SPacket$Status;
accessible	field	net/minecraft/network/packet/c2s/play/ClientSettingsC2SPacket	language	Ljava/lang/String;
accessible	field	net/minecraft/network/packet/c2s/play/ClientSettingsC2SPacket	viewDistance	I
accessible	field	net/minecraft/network/packet/s2c/play/BlockUpdateS2CPacket	state	Lnet/minecraft/block/BlockState;
accessible	field	net/minecraft/network/packet/s2c/play/PlayerListHeaderS2CPacket	footer	Lnet/minecraft/text/Text;
accessible	field	net/minecraft/network/packet/s2c/play/PlayerListHeaderS2CPacket	header	Lnet/minecraft/text/Text;
accessible	field	net/minecraft/network/packet/s2c/play/PlayerSpawnPositionS2CPacket	pos	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/village/raid/RaidManager	raids	Ljava/util/Map;
accessible	field	net/minecraft/entity/player/PlayerAbilities	flySpeed	F
accessible	field	net/minecraft/entity/player/PlayerAbilities	walkSpeed	F
accessible	field	net/minecraft/server/world/ChunkHolder	lastTickLevel	I
accessible	field	net/minecraft/server/world/ChunkHolder	playersWatchingChunkProvider	Lzr$d;
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage$EntityTracker	playersTracking	Ljava/util/Set;
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage	ticketManager	Lzs$a;
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage	chunkGenerator	Lnet/minecraft/world/gen/chunk/ChunkGenerator;
accessible	method	net/minecraft/server/world/ThreadedAnvilChunkStorage	save	(Lnet/minecraft/world/chunk/Chunk;)Z
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage	entityTrackers	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage	unloadedChunks	Lit/unimi/dsi/fastutil/longs/LongSet;
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage	currentChunkHolders	Lit/unimi/dsi/fastutil/longs/Long2ObjectLinkedOpenHashMap;
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage	chunkHolders	Lit/unimi/dsi/fastutil/longs/Long2ObjectLinkedOpenHashMap;
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage	world	Lnet/minecraft/server/world/ServerWorld;
accessible	field	net/minecraft/server/world/ThreadedAnvilChunkStorage	worldGenerationProgressListener	Lnet/minecraft/server/WorldGenerationProgressListener;
accessible	field	net/minecraft/server/PlayerManager	saveHandler	Lnet/minecraft/world/WorldSaveHandler;
accessible	field	net/minecraft/server/PlayerManager	players	Ljava/util/List;
accessible	method	net/minecraft/server/PlayerManager	sendScoreboard	(Lnet/minecraft/scoreboard/ServerScoreboard;Lnet/minecraft/server/network/ServerPlayerEntity;)V
accessible	field	net/minecraft/server/dedicated/AbstractPropertiesHandler	properties	Ljava/util/Properties;
accessible	field	net/minecraft/village/raid/Raid	badOmenLevel	I
accessible	field	net/minecraft/village/raid/Raid	heroesOfTheVillage	Ljava/util/Set;
accessible	field	net/minecraft/village/raid/Raid	waveCount	I
accessible	field	net/minecraft/village/raid/Raid	ticksActive	J
accessible	field	net/minecraft/village/raid/Raid	totalHealth	F
accessible	field	net/minecraft/recipe/book/RecipeBook	recipes	Ljava/util/Set;
accessible	method	net/minecraft/recipe/Ingredient$StackEntry	<init>	(Lnet/minecraft/item/ItemStack;)V
accessible	method	net/minecraft/recipe/Ingredient	<init>	(Ljava/util/stream/Stream;)V
accessible	method	net/minecraft/recipe/Ingredient	cacheMatchingStacks	()V
accessible	field	net/minecraft/recipe/Ingredient	matchingStacks	[Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/world/storage/RegionBasedStorage	cachedRegionFiles	Lit/unimi/dsi/fastutil/longs/Long2ObjectLinkedOpenHashMap;
accessible	field	net/minecraft/scoreboard/ScoreboardObjective	displayName	Lnet/minecraft/text/Text;
accessible	field	net/minecraft/screen/slot/Slot	index	I
accessible	field	net/minecraft/server/world/ChunkTicket	argument	Ljava/lang/Object;
accessible	field	net/minecraft/block/entity/BannerBlockEntity	baseColor	Lnet/minecraft/util/DyeColor;
accessible	field	net/minecraft/block/entity/BannerBlockEntity	patternListTag	Lnet/minecraft/nbt/ListTag;
accessible	method	net/minecraft/block/entity/BarrelBlockEntity	setOpen	(Lnet/minecraft/block/BlockState;Z)V
accessible	method	net/minecraft/block/entity/BarrelBlockEntity	playSound	(Lnet/minecraft/block/BlockState;Lnet/minecraft/sound/SoundEvent;)V
accessible	field	net/minecraft/block/entity/BeaconBlockEntity	lock	Lnet/minecraft/inventory/ContainerLock;
accessible	field	net/minecraft/block/entity/BeaconBlockEntity	customName	Lnet/minecraft/text/Text;
accessible	field	net/minecraft/block/entity/BeaconBlockEntity	level	I
accessible	field	net/minecraft/block/entity/BeaconBlockEntity	primary	Lnet/minecraft/entity/effect/StatusEffect;
accessible	field	net/minecraft/block/entity/BeaconBlockEntity	secondary	Lnet/minecraft/entity/effect/StatusEffect;
accessible	field	net/minecraft/block/entity/BedBlockEntity	color	Lnet/minecraft/util/DyeColor;
accessible	field	net/minecraft/block/entity/BeehiveBlockEntity	flowerPos	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/block/entity/BrewingStandBlockEntity	brewTime	I
accessible	field	net/minecraft/block/entity/BrewingStandBlockEntity	fuel	I
accessible	field	net/minecraft/block/entity/CampfireBlockEntity	cookingTimes	[I
accessible	field	net/minecraft/block/entity/CampfireBlockEntity	cookingTotalTimes	[I
accessible	method	net/minecraft/block/entity/ChestBlockEntity	playSound	(Lnet/minecraft/sound/SoundEvent;)V
accessible	field	net/minecraft/block/entity/ChestBlockEntity	viewerCount	I
accessible	field	net/minecraft/block/entity/LockableContainerBlockEntity	lock	Lnet/minecraft/inventory/ContainerLock;
accessible	field	net/minecraft/block/entity/LockableContainerBlockEntity	customName	Lnet/minecraft/text/Text;
accessible	field	net/minecraft/block/entity/EndGatewayBlockEntity	age	J
accessible	field	net/minecraft/block/entity/EndGatewayBlockEntity	exactTeleport	Z
accessible	field	net/minecraft/block/entity/EndGatewayBlockEntity	exitPortalPos	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/block/entity/AbstractFurnaceBlockEntity	burnTime	I
accessible	field	net/minecraft/block/entity/AbstractFurnaceBlockEntity	cookTime	I
accessible	field	net/minecraft/block/entity/AbstractFurnaceBlockEntity	cookTimeTotal	I
accessible	field	net/minecraft/block/entity/LecternBlockEntity	inventory	Lnet/minecraft/inventory/Inventory;
accessible	method	net/minecraft/block/entity/LecternBlockEntity	setCurrentPage	(I)V
accessible	field	net/minecraft/block/entity/LootableContainerBlockEntity	lootTableId	Lnet/minecraft/util/Identifier;
accessible	field	net/minecraft/block/entity/LootableContainerBlockEntity	lootTableSeed	J
accessible	field	net/minecraft/block/entity/ShulkerBoxBlockEntity	viewerCount	I
accessible	field	net/minecraft/block/entity/SignBlockEntity	editable	Z
accessible	field	net/minecraft/block/entity/SignBlockEntity	text	[Lnet/minecraft/text/Text;
accessible	field	net/minecraft/block/entity/SkullBlockEntity	owner	Lcom/mojang/authlib/GameProfile;
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	author	Ljava/lang/String;
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	ignoreEntities	Z
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	integrity	F
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	metadata	Ljava/lang/String;
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	mirror	Lnet/minecraft/util/BlockMirror;
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	offset	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	rotation	Lnet/minecraft/util/BlockRotation;
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	seed	J
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	showAir	Z
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	showBoundingBox	Z
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	size	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/block/entity/StructureBlockBlockEntity	mode	Lnet/minecraft/block/enums/StructureBlockMode;
accessible	field	net/minecraft/world/World	thread	Ljava/lang/Thread;
accessible	field	net/minecraft/world/World	properties	Lnet/minecraft/world/MutableWorldProperties;
accessible	field	net/minecraft/item/map/MapState	updateTrackersByPlayer	Ljava/util/Map;
accessible	field	net/minecraft/world/PersistentStateManager	loadedStates	Ljava/util/Map;
accessible	field	net/minecraft/server/world/ServerWorld	entitiesById	Lit/unimi/dsi/fastutil/ints/Int2ObjectMap;
accessible	field	net/minecraft/server/world/ServerWorld	worldProperties	Lnet/minecraft/world/level/ServerWorldProperties;
accessible	field	net/minecraft/screen/ScreenHandler	trackedStacks	Lnet/minecraft/util/collection/DefaultedList;
accessible	field	net/minecraft/screen/ScreenHandler	slots	Ljava/util/List;
accessible	field	net/minecraft/recipe/RecipeManager	recipes	Ljava/util/Map;
accessible	field	net/minecraft/resource/ServerResourceManager	commandManager	Lnet/minecraft/server/command/CommandManager;
accessible	field	net/minecraft/server/dedicated/MinecraftDedicatedServer	propertiesLoader	Lnet/minecraft/server/dedicated/ServerPropertiesLoader;
accessible	field	net/minecraft/entity/AreaEffectCloudEntity	effects	Ljava/util/List;
accessible	field	net/minecraft/entity/mob/MobEntity	goalSelector	Lnet/minecraft/entity/ai/goal/GoalSelector;
accessible	field	net/minecraft/entity/mob/MobEntity	targetSelector	Lnet/minecraft/entity/ai/goal/GoalSelector;
accessible	field	net/minecraft/entity/LivingEntity	damageTracker	Lnet/minecraft/entity/damage/DamageTracker;
accessible	field	net/minecraft/entity/LivingEntity	defaultMaxHealth	I
accessible	field	net/minecraft/item/ItemStack	item	Lnet/minecraft/item/Item;
accessible	field	net/minecraft/village/TradeOffer	firstBuyItem	Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/village/TradeOffer	secondBuyItem	Lnet/minecraft/item/ItemStack;
accessible	field	net/minecraft/village/TradeOffer	maxUses	I
accessible	field	net/minecraft/server/MinecraftServer	session	Lnet/minecraft/world/level/storage/LevelStorage$Session;
accessible	field	net/minecraft/server/MinecraftServer	saveProperties	Lnet/minecraft/world/SaveProperties;
accessible	field	net/minecraft/server/MinecraftServer	networkIo	Lnet/minecraft/server/ServerNetworkIo;
accessible	field	net/minecraft/server/world/ChunkTicketType	expiryTicks	J
accessible	field	net/minecraft/world/level/LevelInfo	hardcore	Z
accessible	field	net/minecraft/world/level/LevelInfo	name	Ljava/lang/String;

accessible	method	net/minecraft/block/DropperBlock	dispense	(Lnet/minecraft/server/world/ServerWorld;Lnet/minecraft/util/math/BlockPos;)V
accessible	method	net/minecraft/entity/decoration/ItemFrameEntity	setFacing	(Lnet/minecraft/util/math/Direction;)V
accessible	method	net/minecraft/entity/mob/MagmaCubeEntity	setSize	(IZ)V
accessible	method	net/minecraft/entity/player/PlayerEntity	getBurningDuration	()I
accessible	method	net/minecraft/entity/passive/RabbitEntity	initGoals	()V
accessible	field	net/minecraft/server/MinecraftServer	LOGGER	Lorg/apache/logging/log4j/Logger;

# Fixing package-private issues
#accessible	field	net/minecraft/entity/LivingEntity drops
#accessible	field	net/minecraft/entity/LivingEntity forceDrops
accessible	method	net/minecraft/entity/projectile/ProjectileEntity updateRotation	(FF)F
accessible	field	net/minecraft/entity/mob/DrownedEntity landNavigation	Lnet/minecraft/entity/ai/pathing/MobNavigation;
accessible	field	net/minecraft/entity/mob/DrownedEntity waterNavigation	Lnet/minecraft/entity/ai/pathing/SwimNavigation;
accessible	method	net/minecraft/screen/slot/Slot onTake	(I)V
accessible	field	net/minecraft/entity/Entity dataTracker	Lnet/minecraft/entity/data/DataTracker;
accessible	method	net/minecraft/entity/Entity isLevelAtLeast	(Lnet/minecraft/server/NBTTagCompound;I)Z
accessible	field	net/minecraft/block/AbstractBlock soundGroup	Lnet/minecraft/sound/BlockSoundGroup;
accessible	method	net/minecraft/server/MinecraftServer createTask	(Ljava/lang/Runnable;)Ljava/lang/Runnable;
accessible	field	net/minecraft/block/entity/BlockEntity world	Lnet/minecraft/world/World;
accessible	field	net/minecraft/block/entity/BlockEntity pos	Lnet/minecraft/util/math/BlockPos;
accessible	field	net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket changePosition	Z
accessible	field	net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket changeLook	Z
accessible	field	net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket x	D
accessible	field	net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket y	D
accessible	field	net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket z	D
accessible	field	net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket pitch	F
accessible	field	net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket yaw	F
accessible	method	net/minecraft/block/Block dropExperience	(Lnet/minecraft/server/world/ServerWorld;Lnet/minecraft/util/math/BlockPos;I)V
accessible	field	net/minecraft/world/World rainGradient F
accessible	field	net/minecraft/world/World thunderGradient	F
accessible	method	net/minecraft/world/World getTileEntity	(Lnet/minecraft/server/BlockPosition;Z)Lnet/minecraft/server/TileEntity;
